# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09440c5dc086f352e01121866f3d64f54a93bfbfa23c95aaddabba5763fd813bc85cb29f568c09219970f6cc7d9a59a47746951acaf9bb2b65ad9cbeb248cbdb

test:
  secret_key_base: 7070f6cb1e622424035776eea3f86c5393bf8efdf3c6e6bab6fb357ba940a7da8d6f535c505dd667e4abe4aa0fafa3ee25106c13d85c74ea22721d9909a982f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
